project: 
  type: manuscript

manuscript:
  meca-bundle: "bundle_pargent_2023.zip"
  code-links: [binder, repo]
  notebooks:
    - notebook: electronic_supplemental_material.qmd
      title: Electronic Supplemental Material
    - notebook: sensitivity_analysis.qmd
      title: Sensitivity Analysis
  
format:
  html:
    toc: true
    comments:
      hypothesis: false
    theme: pulse
  jats: default
  apaquarto-pdf:
    documentmode: jou
  apaquarto-docx: default

execute:
  freeze: auto